"""What Minecraft actually says about blocks - the query side of `mcbuild/data/blocks.json`.

That file is generated by `tools/extract_blocks.py` from two authoritative sources: Mojang's own data
generator (registry, every state property, every legal value) and the client jar's textures (real
colours). 1196 blocks, 32366 states, 1193 colours on 26.2. Nothing here is remembered or guessed.

What it is for:

    exists / kind / props / default   does this block exist, what is it, what states does it take
    validate                          is this exact block+state LEGAL - the check that used to happen
                                      in game, an hour later, when Litematica refused to place it
    color / nearest / ramp            pick blocks by colour, out of all 1193, not out of a hand list
    is_full_cube / supports_top       the clinging and standing rules, derived from block TYPE

`is_full_cube` matters more than it looks. CLAUDE.md rule 9 exists because "solid" was once taken to
mean "not air", so vines were hung off wall blocks and fell. A wall is not a full cube and the game
knows it - we just never asked.
"""
from __future__ import annotations

import functools
import json
import math
import pathlib

DATA = pathlib.Path(__file__).resolve().parent / "data/blocks.json"
SERVER = pathlib.Path(__file__).resolve().parent / "data/server_blocks.json"

# Types that do NOT fill the whole cube. Everything else does. Stated as the exclusion list because
# it is the shorter and far more stable half - new full blocks arrive every update, new SHAPES rarely.
NOT_FULL = {
    "air", "cave_air", "void_air", "structure_void", "light", "barrier",
    # cut geometry
    "slab", "stair", "wall", "fence", "fence_gate", "door", "trapdoor", "shelf",
    "button", "pressure_plate", "weighted_pressure_plate", "scaffolding", "bed", "cake",
    "candle", "candle_cake", "cauldron", "layered_cauldron", "lava_cauldron", "hopper",
    "brewing_stand", "anvil", "grindstone", "stonecutter", "lectern", "bell", "campfire",
    "chest", "trapped_chest", "ender_chest", "copper_chest", "weathering_copper_chest",
    "enchantment_table", "daylight_detector", "beacon", "conduit", "decorated_pot",
    "flower_pot", "end_portal_frame", "dragon_egg", "turtle_egg", "sniffer_egg", "heavy_core",
    "sculk_sensor", "calibrated_sculk_sensor", "sculk_shrieker", "composter", "piston_head",
    "moving_piston", "snow_layer", "farmland", "dirt_path", "powder_snow", "end_rod",
    "lightning_rod", "weathering_lightning_rod", "copper_golem_statue",
    "weathering_copper_golem_statue", "weathering_copper_grate", "pointed_dripstone",
    "amethyst_cluster", "sea_pickle", "frogspawn", "lily_pad", "web", "sulfur_spike",
    # attachments and thin things
    "torch", "wall_torch", "redstone_torch", "redstone_wall_torch", "soul_fire", "fire",
    "ladder", "lever", "lantern", "weathering_lantern", "chain", "weathering_copper_chain",
    "iron_bars", "weathering_copper_bar", "stained_glass_pane", "glow_lichen", "multiface",
    "sculk_vein", "vine", "rail", "powered_rail", "detector_rail", "redstone_wire",
    # NOTE: `bonemealable_feature_placer` is moss_block and pale_moss_block - the type name
    # describes bonemealing, not shape, and both are full cubes. It does not belong here.
    "repeater", "comparator", "tripwire", "trip_wire_hook", "carpet", "wool_carpet",
    "mossy_carpet", "leaf_litter", "flower_bed", "standing_sign", "wall_sign",
    "ceiling_hanging_sign", "wall_hanging_sign", "banner", "wall_banner", "skull",
    "player_head", "player_wall_head", "wall_skull", "wither_skull", "wither_wall_skull",
    "piglinwallskull", "cocoa", "hanging_moss", "hanging_roots",
    # growing things
    "flower", "tall_flower", "double_plant", "tall_grass", "grass", "bush", "sapling", "crop",
    "carrot", "potato", "beetroot", "stem", "attached_stem", "nether_wart", "sweet_berry_bush",
    "cactus", "cactus_flower", "sugar_cane", "bamboo_stalk", "bamboo_sapling", "azalea",
    "mangrove_propagule", "nether_fungus", "nether_roots", "nether_sprouts", "dry_vegetation",
    "short_dry_grass", "tall_dry_grass", "firefly_bush", "eyeblossom", "wither_rose",
    "pitcher_crop", "torchflower_crop", "big_dripleaf", "big_dripleaf_stem", "small_dripleaf",
    "spore_blossom", "chorus_flower", "chorus_plant", "kelp", "kelp_plant", "seagrass",
    "tall_seagrass", "twisting_vines", "twisting_vines_plant", "weeping_vines",
    "weeping_vines_plant", "cave_vines", "cave_vines_plant", "coral", "coral_fan",
    "coral_plant", "coral_wall_fan", "base_coral_fan", "base_coral_plant",
    "base_coral_wall_fan",
    # not a block you can build against
    "liquid", "bubble_column", "nether_portal", "end_portal", "end_gateway",
}
# Not full cubes, but you can stand on them and plants root in them.
STANDABLE_PARTIAL = {"farmland", "dirt_path", "snow_layer", "slab", "stair"}
# Gravity. These fall the instant nothing holds them, so they cannot be used anywhere a design has
# air underneath - which for a statue in the void is nearly everywhere. `red_sand` is the trap: it is
# the best orange in the game and cheap, and it would have poured the giraffe into the void.
FALLING = {"sand", "colored_falling", "concrete_powder", "brushable", "anvil", "dragon_egg"}
AIRY = {"air", "cave_air", "void_air"}


@functools.lru_cache(maxsize=1)
def _db() -> dict:
    if not DATA.exists():
        return {}
    return json.loads(DATA.read_text(encoding="utf-8"))


@functools.lru_cache(maxsize=1)
def _server() -> dict:
    """The SERVER's block list. The client runs 26.2; skyblock.net runs 1.19, and a block added after
    1.19 exists in the client registry, renders, audits clean - and cannot be placed."""
    if not SERVER.exists():
        return {}
    return json.loads(SERVER.read_text(encoding="utf-8"))


def server_version() -> str:
    return _server().get("version", "")


def server_authoritative() -> bool:
    """True only when the list came from the server version's OWN registry dump, not from captures."""
    return bool(_server().get("authoritative"))


def available(name: str) -> bool:
    """Can this actually be placed on the server. Falls back to `exists` if no server list is set."""
    srv = _server()
    if not srv:
        return exists(name)
    return _short(name) in set(srv.get("blocks", ()))


def _short(name: str) -> str:
    return name.split("[", 1)[0].split(":", 1)[-1].strip()


def loaded() -> bool:
    """False if the knowledge base was never generated - callers fall back to their own rules."""
    return bool(_db())


# ------------------------------------------------------------------ identity

def exists(name: str) -> bool:
    return _short(name) in _db()


def kind(name: str) -> str:
    return (_db().get(_short(name)) or {}).get("type", "")


def props(name: str) -> dict:
    """{property: [legal values]} for this block."""
    return (_db().get(_short(name)) or {}).get("props", {})


def default(name: str) -> dict:
    return (_db().get(_short(name)) or {}).get("default", {})


def is_full_cube(name: str) -> bool:
    """A full 16x16x16 block. What a vine, ladder, torch or painting needs to cling to."""
    n = _short(name)
    if n not in _db():
        return False
    return kind(n) not in NOT_FULL


def falls(name: str) -> bool:
    """Gravity-affected: unsupported, it drops. Never build a floating shape out of one."""
    return kind(name) in FALLING


def supports_top(name: str) -> bool:
    """Can something stand, or be placed, on top of this."""
    n = _short(name)
    return is_full_cube(n) or kind(n) in STANDABLE_PARTIAL


# ------------------------------------------------------------------ validation

def validate(name: str, state: dict | None = None) -> list[str]:
    """Every reason this block+state could not be placed. Empty list means it is legal.

    This is the check that used to be outsourced to Litematica, in game, long after the design shipped.
    """
    n = _short(name)
    if not _db():
        return []
    if n not in _db():
        return [f"no such block: {n}"]
    legal, bad = props(n), []
    for k, v in (state or {}).items():
        if k not in legal:
            bad.append(f"{n}: no property {k!r} (has {sorted(legal) or 'none'})")
        elif str(v) not in legal[k]:
            bad.append(f"{n}[{k}={v}]: not a legal value (want {legal[k]})")
    return bad


# ------------------------------------------------------------------ colour

def color(name: str) -> tuple[int, int, int] | None:
    rgb = (_db().get(_short(name)) or {}).get("rgb")
    return tuple(rgb) if rgb else None


def _dist(a, b) -> float:
    """Perceptual-ish distance. Plain RGB puts orange next to brown; weighting green and red the way
    the eye does keeps a coat's blotches distinct from its ground."""
    dr, dg, db = a[0] - b[0], a[1] - b[1], a[2] - b[2]
    rm = (a[0] + b[0]) / 2
    return math.sqrt((2 + rm / 256) * dr * dr + 4 * dg * dg + (2 + (255 - rm) / 256) * db * db)


def candidates(full_only: bool = True, tier: set[str] | None = None, exclude: tuple = (),
               allow_falling: bool = False, server_only: bool = True) -> list[str]:
    """Every block worth considering for a surface.

    `server_only` is ON by default: picking a colour out of the 26.2 registry when the server is 1.19
    would quietly choose blocks that cannot be placed. Excludes gravity blocks unless you ask."""
    from . import palette
    out = []
    for n, rec in _db().items():
        if "rgb" not in rec or n in AIRY:
            continue
        if server_only and not available(n):
            continue
        if full_only and not is_full_cube(n):
            continue
        if not allow_falling and falls(n):
            continue
        if any(s in n for s in exclude):
            continue
        if tier and palette.tier(n) not in tier:
            continue
        out.append(n)
    return sorted(out)


def nearest(rgb, pool: list[str] | None = None, **kw) -> str | None:
    """The block closest to a colour. Searches all 1193 by default, not a hand-written shortlist."""
    pool = pool if pool is not None else candidates(**kw)
    best, bd = None, float("inf")
    for n in pool:
        c = color(n)
        if not c:
            continue
        d = _dist(rgb, c)
        if d < bd:
            best, bd = n, d
    return best


def ramp(a, b, steps: int, pool: list[str] | None = None, **kw) -> list[str]:
    """A shading ladder between two colours - `steps` distinct blocks, in order.

    Duplicates are dropped rather than repeated: a ramp that lands on the same block twice reads as a
    flat band, and it is better to know the palette only had four usable rungs than to pretend it had six.
    """
    pool = pool if pool is not None else candidates(**kw)
    out = []
    for i in range(steps):
        t = i / max(1, steps - 1)
        want = tuple(round(a[j] + (b[j] - a[j]) * t) for j in range(3))
        pick = nearest(want, pool=[p for p in pool if p not in out])
        if pick:
            out.append(pick)
    return out


def search(substr: str = "", kind_is: str = "", has_prop: str = "") -> list[str]:
    """Explore the registry. Backs `python -m mcbuild blocks`."""
    out = []
    for n, rec in sorted(_db().items()):
        if substr and substr not in n:
            continue
        if kind_is and rec.get("type") != kind_is:
            continue
        if has_prop and has_prop not in (rec.get("props") or {}):
            continue
        out.append(n)
    return out
