name: Mirror Maze
gen: attractions
params:
  land: hollow
  facing: east
  at:
  - 97573
  - 203
  - 80838
  kind: mirrormaze
  title: Mirror Maze
  under: out/islandright.litematic
finish:
  verify_against: out/islandright.litematic
origin_lock: false
