package dev.jack.chunkscan;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * What a block is MADE of, in game.
 *
 * <p>{@code /cscan bom} stops at the block: it says 518 powered rails and leaves you to work out
 * that this is 3,108 gold ingots, and whether any of it is in a chest. On a server where nothing
 * is mined that is the only question there is.
 *
 * <p>The data is {@code chunkscan_recipes.json}, GENERATED by {@code tools/export_rules.py} from
 * the client jar's own 1,585 recipe files — not typed here. It is baked into the jar rather than
 * read from the schematics folder because recipes change when the GAME changes, which is the same
 * test that decided where {@code chunkscan_rules.json} lives.
 *
 * <p>The algorithm is a port of {@code mcbuild/recipes.py} and the four things it has to get
 * right are the same four, each of which is a way to be confidently wrong:
 *
 * <ul>
 *   <li><b>Cycles.</b> iron_ingot → iron_block → 9 iron_ingot. Every recursion carries its path.</li>
 *   <li><b>Packing recipes are ARBITRAGE, not routes.</b> Costing every leaf at one unit makes a
 *       raw_gold_block a cheaper source of raw gold than raw gold is, because 1 becomes 9 for
 *       free. The Python resolver planned 518 rails out of 58 gold blocks nobody owns before this
 *       was caught — and the cycle guard did not stop it, because a cycle guard stops the
 *       recursion, not the arithmetic. Packing recipes are barred from costing and offered only
 *       against stock you actually hold.</li>
 *   <li><b>Crafting is not always the answer.</b> A recipe that costs the same as the thing it
 *       makes is a wash; following it anyway sends you shopping for its ingredients instead.</li>
 *   <li><b>An alternatives list is resolved by what you HAVE.</b> A stick takes any of fourteen
 *       planks. Picking the first one in the file sends you out for oak while 3,000 jungle planks
 *       sit in a chest.</li>
 * </ul>
 *
 * <p>Dirt is CURRENCY here, so a route that spends it carries a heavy penalty rather than a ban —
 * if it is genuinely the only path the answer still says so, loudly, instead of reporting the item
 * as unobtainable.
 */
final class Recipes {
	private static final String RESOURCE = "/chunkscan_recipes.json";
	private static final double CURRENCY_PENALTY = 1000.0;
	private static final int MAX_DEPTH = 16;

	/** One recipe: what it makes, how many, and what it eats. */
	record Recipe(String id, String item, String kind, int count, List<Slot> needs, boolean reversible,
	              List<List<String>> grid) {}

	/** One ingredient slot: any of {@code alts} will do, {@code n} of them per craft. */
	record Slot(List<String> alts, int n) {}

	/** One line of the answer. */
	record Step(String recipe, String item, String kind, int times, int made, Map<String, Integer> from) {}

	private static final Map<String, List<Recipe>> BY_ITEM = new HashMap<>();
	private static final Map<String, Double> COST = new HashMap<>();
	private static boolean loaded;

	private Recipes() {}

	static synchronized void load() {
		if (loaded) return;
		loaded = true;
		try (InputStream in = Recipes.class.getResourceAsStream(RESOURCE)) {
			if (in == null) return;                 // ship without it and `craft` says so
			JsonObject root = JsonParser.parseReader(new InputStreamReader(in, StandardCharsets.UTF_8)).getAsJsonObject();
			JsonObject recs = root.getAsJsonObject("recipes");
			for (var e : recs.entrySet()) {
				List<Recipe> list = new ArrayList<>();
				for (var v : e.getValue().getAsJsonArray()) {
					JsonObject r = v.getAsJsonObject();
					List<Slot> needs = new ArrayList<>();
					for (var sv : r.getAsJsonArray("needs")) {
						JsonObject s = sv.getAsJsonObject();
						List<String> alts = new ArrayList<>();
						JsonArray a = s.getAsJsonArray("alts");
						for (var x : a) alts.add(x.getAsString());
						needs.add(new Slot(alts, s.get("n").getAsInt()));
					}
					// The real 3x3 layout, when the recipe has one. `needs` is an aggregate, which
					// is all a COST needs and not enough to CRAFT: six stone bricks anywhere in the
					// grid do not make stairs.
					List<List<String>> grid = null;
					if (r.has("grid")) {
						grid = new ArrayList<>();
						for (var gv : r.getAsJsonArray("grid")) {
							List<String> cell = new ArrayList<>();
							for (var x : gv.getAsJsonArray()) cell.add(x.getAsString());
							grid.add(cell);
						}
					}
					list.add(new Recipe(r.get("id").getAsString(), e.getKey(), r.get("kind").getAsString(),
						r.get("count").getAsInt(), needs,
						r.has("reversible") && r.get("reversible").getAsBoolean(), grid));
				}
				BY_ITEM.put(e.getKey(), list);
			}
		} catch (Exception e) {
			ChunkScanClient.LOG.warn("chunkscan_recipes.json unreadable, /cscan craft is off: {}", e.toString());
		}
	}

	static boolean available() {
		load();
		return !BY_ITEM.isEmpty();
	}

	static String shortName(String n) {
		return Rules.shortName(n);
	}

	static List<Recipe> ways(String item) {
		load();
		return BY_ITEM.getOrDefault(shortName(item), List.of());
	}

	private static double leafCost(String item) {
		return Rules.isCurrency(item) ? CURRENCY_PENALTY : 1.0;
	}

	/**
	 * Base units one of {@code item} costs by the cheapest chain, per OUTPUT unit — so a
	 * stonecutter recipe (1 → 1) beats a crafting one (6 → 4) on the ratio that matters.
	 */
	static double rawCost(String item) {
		return rawCost(shortName(item), new HashSet<>(), 0);
	}

	private static double rawCost(String item, Set<String> path, int depth) {
		if (path.contains(item) || depth > MAX_DEPTH) return Double.POSITIVE_INFINITY;
		if (path.isEmpty()) {
			Double memo = COST.get(item);
			if (memo != null) return memo;
		}
		double best = leafCost(item);
		Set<String> next = new HashSet<>(path);
		next.add(item);
		for (Recipe r : ways(item)) {
			if (r.reversible()) continue;
			double tot = perUnit(r, next, depth);
			if (!Double.isInfinite(tot) && tot < best) best = tot;
		}
		if (path.isEmpty()) COST.put(item, best);
		return best;
	}

	private static double perUnit(Recipe r, Set<String> path, int depth) {
		double tot = 0.0;
		for (Slot s : r.needs()) {
			double alt = Double.POSITIVE_INFINITY;
			for (String a : s.alts()) alt = Math.min(alt, rawCost(a, path, depth + 1));
			if (Double.isInfinite(alt)) return Double.POSITIVE_INFINITY;
			tot += alt * s.n();
		}
		return tot / Math.max(1, r.count());
	}

	private static Recipe best(String item, Set<String> path) {
		Recipe best = null;
		double bestCost = Double.POSITIVE_INFINITY;
		for (Recipe r : ways(item)) {
			if (r.reversible()) continue;
			boolean cyc = false;
			for (Slot s : r.needs()) for (String a : s.alts()) if (path.contains(a)) cyc = true;
			if (cyc) continue;
			double c = perUnit(r, path, 0);
			if (c < bestCost) { best = r; bestCost = c; }
		}
		return best;
	}

	/** What you HAVE MOST OF wins; ties go to the cheapest to make. */
	private static String pick(List<String> alts, Map<String, Integer> stock) {
		List<String> real = new ArrayList<>();
		for (String a : alts) if (!Rules.isCurrency(a)) real.add(a);
		if (real.isEmpty()) real = alts;
		return real.stream()
			.max(Comparator.<String>comparingInt(a -> stock.getOrDefault(a, 0))
				.thenComparing(a -> -rawCost(a)))
			.orElse(alts.get(0));
	}

	/** The answer: steps in order, what came out of your containers, what is still missing. */
	static final class Plan {
		final List<Step> steps = new ArrayList<>();
		final Map<String, Integer> used = new LinkedHashMap<>();
		final Map<String, Integer> shortOf = new LinkedHashMap<>();
		final Set<String> currency = new HashSet<>();

		int smelts() {
			int n = 0;
			for (Step s : steps) if (s.kind().equals("smelt") || s.kind().equals("cook")) n += s.made();
			return n;
		}
	}

	private static void add(Map<String, Integer> m, String k, int v) {
		m.merge(k, v, Integer::sum);
	}

	/**
	 * Resolve {@code want} down to raw materials, spending {@code have} on the way.
	 *
	 * <p>{@code have} is consumed as the walk goes, so two targets needing the same ingredient
	 * cannot both be told the whole stock is theirs — the same allocate-in-rank-order rule
	 * {@link Plan} already follows for build spots.
	 */
	static Plan plan(Map<String, Integer> want, Map<String, Integer> have) {
		load();
		Plan p = new Plan();
		Map<String, Integer> stock = new HashMap<>();
		have.forEach((k, v) -> add(stock, shortName(k), v));
		Map<String, Integer> times = new LinkedHashMap<>();
		Map<String, Recipe> recipeOf = new HashMap<>();
		Map<String, Map<String, Integer>> ingredientsOf = new HashMap<>();
		Map<String, Integer> depthOf = new HashMap<>();

		for (var e : want.entrySet()) {
			if (e.getValue() > 0) {
				need(shortName(e.getKey()), e.getValue(), new HashSet<>(), 0,
					p, stock, times, recipeOf, ingredientsOf, depthOf);
			}
		}
		// DEEPEST FIRST: a recipe cannot run before the things it eats exist, and the same recipe
		// can be reached from several targets at different depths.
		List<String> order = new ArrayList<>(times.keySet());
		order.sort((a, b) -> depthOf.getOrDefault(b, 0) - depthOf.getOrDefault(a, 0));
		for (String rid : order) {
			Recipe r = recipeOf.get(rid);
			p.steps.add(new Step(rid, r.item(), r.kind(), times.get(rid), times.get(rid) * r.count(),
				ingredientsOf.getOrDefault(rid, Map.of())));
		}
		return p;
	}

	private static int need(String item, int qty, Set<String> path, int depth, Plan p,
	                        Map<String, Integer> stock, Map<String, Integer> times,
	                        Map<String, Recipe> recipeOf, Map<String, Map<String, Integer>> ingredientsOf,
	                        Map<String, Integer> depthOf) {
		int take = Math.min(qty, stock.getOrDefault(item, 0));
		if (take > 0) {
			stock.put(item, stock.get(item) - take);
			add(p.used, item, take);
			qty -= take;
		}
		if (qty <= 0) return depth;

		// Unpack a block you ALREADY HAVE before making anything: a chest of gold blocks is nine
		// times as much gold and no trip. Barred from the cost model, allowed here against stock.
		for (Recipe r : ways(item)) {
			if (!r.reversible() || qty <= 0 || r.needs().size() != 1) continue;
			Slot s = r.needs().get(0);
			String src = null;
			for (String a : s.alts()) if (stock.getOrDefault(a, 0) > 0) { src = a; break; }
			if (src == null) continue;
			int runs = Math.min(stock.get(src) / s.n(), ceilDiv(qty, r.count()));
			if (runs <= 0) continue;
			stock.put(src, stock.get(src) - runs * s.n());
			add(p.used, src, runs * s.n());
			add(times, r.id(), runs);
			recipeOf.put(r.id(), r);
			add(ingredientsOf.computeIfAbsent(r.id(), k -> new LinkedHashMap<>()), src, runs * s.n());
			depthOf.merge(r.id(), depth, Math::max);
			int made = runs * r.count();
			if (made > qty) add(stock, item, made - qty);
			qty -= Math.min(qty, made);
		}
		if (qty <= 0) return depth;
		if (depth > MAX_DEPTH) { add(p.shortOf, item, qty); return depth; }

		Recipe r = best(item, path);
		// Craft when it is genuinely cheaper, or when you already hold an ingredient. Otherwise
		// say you are short of the ITEM, which is the thing you would actually go and buy.
		if (r != null && perUnit(r, path, 0) >= leafCost(item)) {
			boolean any = false;
			for (Slot s : r.needs()) for (String a : s.alts()) if (stock.getOrDefault(a, 0) > 0) any = true;
			if (!any) r = null;
		}
		if (r == null) {
			add(p.shortOf, item, qty);
			if (Rules.isCurrency(item)) p.currency.add(item);
			return depth;
		}
		int n = ceilDiv(qty, r.count());
		add(times, r.id(), n);
		recipeOf.put(r.id(), r);
		Set<String> next = new HashSet<>(path);
		next.add(item);
		int deepest = depth;
		for (Slot s : r.needs()) {
			String chosen = pick(s.alts(), stock);
			add(ingredientsOf.computeIfAbsent(r.id(), k -> new LinkedHashMap<>()), chosen, s.n() * n);
			deepest = Math.max(deepest, need(chosen, s.n() * n, next, depth + 1,
				p, stock, times, recipeOf, ingredientsOf, depthOf));
		}
		int made = n * r.count();
		if (made > qty) add(stock, item, made - qty);
		depthOf.merge(r.id(), deepest, Math::max);
		return deepest;
	}

	private static int ceilDiv(int a, int b) {
		return (a + b - 1) / Math.max(1, b);
	}
}
