name: Dead Tree 3
gen: hollowmanor
params:
  land: hollow
  facing: north
  at:
  - 97628
  - 203
  - 80828
  kind: deadtree
  title: Dead Tree 3
  under: out/islandright.litematic
finish:
  verify_against: out/islandright.litematic
origin_lock: false
