name: Dead Tree
gen: hollowmanor
params:
  land: hollow
  facing: south
  at:
  - 97610
  - 203
  - 80796
  kind: deadtree
  title: Dead Tree
  under: out/islandright.litematic
finish:
  verify_against: out/islandright.litematic
origin_lock: false
