name: Duel 2
gen: casino
params:
  outcomes: 3
  pit: 2
  at:
  - 97607
  - 203
  - 80562
  kind: duel
  title: Duel 2
  under: out/newisle.litematic
finish:
  verify_against: out/newisle.litematic
  defer_to:
  - out/High Roller 1.litematic
  - out/High Roller 2.litematic
  - out/High Roller 3.litematic
  - out/High Roller 4.litematic
  - out/High Roller 5.litematic
  - out/One In Three 1.litematic
  - out/One In Three 2.litematic
  - out/One In Three 3.litematic
  - out/One In Three 4.litematic
  - out/One In Three 5.litematic
  - out/Lucky Two 1.litematic
  - out/Lucky Two 2.litematic
  - out/Lucky Two 3.litematic
  - out/Lucky Two 4.litematic
  - out/Duel 1.litematic
origin_lock: false
