name: Duel 1
gen: casino
params:
  outcomes: 3
  pit: 2
  at:
  - 97586
  - 203
  - 80640
  kind: duel
  title: Duel 1
  under: out/newisle.litematic
finish:
  verify_against: out/newisle.litematic
origin_lock: false
