name: Hall Of Mirrors
gen: attractions
params:
  land: midway
  facing: east
  at:
  - 97577
  - 203
  - 80575
  kind: mirrormaze
  title: Hall Of Mirrors
  under: out/newisle.litematic
finish:
  verify_against: out/newisle.litematic
origin_lock: false
