name: Lucky Two 1
gen: casino
params:
  outcomes: 3
  pit: 2
  at:
  - 97567
  - 203
  - 80613
  kind: lucky_number
  title: Lucky Two 1
  under: out/newisle.litematic
finish:
  verify_against: out/newisle.litematic
  defer_to:
  - out/High Roller 1.litematic
  - out/High Roller 2.litematic
  - out/High Roller 3.litematic
  - out/High Roller 4.litematic
  - out/High Roller 5.litematic
  - out/One In Three 1.litematic
  - out/One In Three 2.litematic
  - out/One In Three 3.litematic
  - out/One In Three 4.litematic
  - out/One In Three 5.litematic
origin_lock: false
