name: Mirror Maze
gen: attractions
params:
  land: hollow
  facing: west
  maze_w: 4
  maze_d: 4
  at:
  - 97603
  - 203
  - 80775
  kind: mirrormaze
  title: Mirror Maze
  under: out/islandright.litematic
finish:
  verify_against: out/islandright.litematic
origin_lock: false
