name: One In Three 4
gen: casino
params:
  outcomes: 3
  pit: 2
  at:
  - 97563
  - 203
  - 80565
  kind: double_or_none
  title: One In Three 4
  under: out/newisle.litematic
finish:
  verify_against: out/newisle.litematic
  defer_to:
  - out/High Roller 1.litematic
  - out/High Roller 2.litematic
  - out/High Roller 3.litematic
  - out/High Roller 4.litematic
  - out/High Roller 5.litematic
  - out/High Roller 6.litematic
  - out/Coin Toss 1.litematic
  - out/Coin Toss 2.litematic
  - out/Coin Toss 3.litematic
  - out/Coin Toss 4.litematic
  - out/Coin Toss 5.litematic
  - out/One In Three 1.litematic
  - out/One In Three 2.litematic
  - out/One In Three 3.litematic
origin_lock: false
