name: One In Three 2
gen: casino
params:
  outcomes: 3
  pit: 2
  at:
  - 97585
  - 203
  - 80565
  kind: double_or_none
  title: One In Three 2
  under: out/newisle.litematic
finish:
  verify_against: out/newisle.litematic
origin_lock: false
