name: Sign Fortune Wheel
gen: wayfinding
params:
  land: hollow
  facing: east
  name: Fortune Wheel
  does:
  - red green black
  - 1 in 3
  at:
  - 97566
  - 203
  - 80802
  kind: marker
  title: Sign Fortune Wheel
  under: out/islandright.litematic
finish:
  verify_against: out/islandright.litematic
origin_lock: false
