name: Sign Mirror Maze
gen: wayfinding
params:
  land: hollow
  facing: east
  name: Mirror Maze
  does:
  - find your way
  - no way back
  at:
  - 97574
  - 203
  - 80806
  kind: marker
  title: Sign Mirror Maze
  under: out/islandright.litematic
finish:
  verify_against: out/islandright.litematic
origin_lock: false
