name: The Monument
gen: monument
params:
  land: midway
  facing: east
  at:
  - 97611
  - 203
  - 80616
  kind: monument
  title: The Monument
  under: out/newisle.litematic
finish:
  verify_against: out/newisle.litematic
origin_lock: false
