name: The Arcade
gen: attractions
params:
  land: midway
  facing: west
  at:
  - 97586
  - 203
  - 80619
  kind: arcade
  title: The Arcade
  under: out/newisle.litematic
finish:
  verify_against: out/newisle.litematic
origin_lock: false
