name: The Mine Head
gen: frontiertown
params:
  land: frontier
  facing: south
  at:
  - 97572
  - 203
  - 80394
  kind: minehead
  title: The Mine Head
  under: out/islandleft.litematic
finish:
  verify_against: out/islandleft.litematic
origin_lock: false
