name: The Mine Head
gen: frontiertown
params:
  land: frontier
  facing: west
  at:
  - 97623
  - 203
  - 80381
  kind: minehead
  title: The Mine Head
  under: out/islandleft.litematic
finish:
  verify_against: out/islandleft.litematic
origin_lock: false
