name: The Monument
gen: monument
params:
  land: midway
  facing: north
  at:
  - 97579
  - 203
  - 80617
  kind: monument
  title: The Monument
  under: out/newisle.litematic
finish:
  verify_against: out/newisle.litematic
origin_lock: false
