name: The Saloon
gen: frontiertown
params:
  land: frontier
  width: 17
  depth: 12
  facing: east
  at:
  - 97564
  - 203
  - 80431
  kind: saloon
  title: The Saloon
  under: out/islandleft.litematic
finish:
  verify_against: out/islandleft.litematic
origin_lock: false
