name: The Crypt
gen: hollowmanor
params:
  land: hollow
  facing: north
  at:
  - 97561
  - 203
  - 80805
  kind: crypt
  title: The Crypt
  under: out/islandright.litematic
finish:
  verify_against: out/islandright.litematic
origin_lock: false
