name: Water Tower
gen: frontiertown
params:
  land: frontier
  facing: north
  at:
  - 97627
  - 203
  - 80395
  kind: watertower
  title: Water Tower
  under: out/islandleft.litematic
finish:
  verify_against: out/islandleft.litematic
origin_lock: false
